### PR TITLE
Ubuntu webapp

### PR DESCRIPTION
**Pull request by rkleiren**
Webapp for ubuntu touch

### CODE REVIEW

**Comment by Psycojoker** [comment]
Do you have a link on how we could easily test that? (I have a Ubuntu but neither use unity)

**Comment by gdesmott** [comment]
Looks like easy enough, much more than Android !

Can you please squash both commits together?

Are you going to publish it to the mobile store?

**Comment by rkleiren** [comment]
@Psycojoker 
You only need to install the [ubuntu sdk](https://developer.ubuntu.com/en/start/ubuntu-sdk/installing-the-sdk/) to get started. It is based on QtCreator. I did a fresh install but I don't know how well it behaves if you already have QtCreator installed. You *might* need to uninstall it first.
Then follow the tutorial on [how to create a webapp](https://developer.ubuntu.com/en/web/tutorials/web-app-tutorial/). When prompted to install a device kit, select the 15.04 framework for i386. This will be used to emulate the environment.

I have an ubuntu phone so I tested the webapp directly on it and it works fine. I didn't test how it behaves on the emulator though. I will do that now.

@gdesmott 
Commits squashed and yes I'll publish it once you've approved it.

**Comment by rkleiren** [comment]
Ok the emulator doesn't have the 15.04 framework but the 14.10 one. This means the 14.10 device kit is required and the version in the manifest.json must be changed too. I tried to install the 14.10 framework but it failed. I'm not yet sure why. I'll get back on this once I have more time

**Comment by gdesmott** [comment]
Merged, thanks for the patch!

Feel free to upload it on the store and then patch the about page to link it. :)

**Pull request merged**
