### PR TITLE
vegoresto.fr: customizations

### PR DESCRIPTION
**Pull request by drzraf**
- legend as an overlayed semi-transparent div (thus overrode home.haml)
- logo points to /about
- use mapbox.com tiles (+attributions)
- dynamically adds a link for mobile (cf followup)

### CODE REVIEW

**Comment by drzraf** [comment]
somehow depends upon PR #19

**Comment by drzraf** [comment]
side note: I can't find the proper way to override tags_to_color(). Advise appreciated.
Could we have a global javascript variable representing python's APP_NAME so that if/else could be used,
or alternatively, (using mustache?) a javascript variables override file?

**Comment by Psycojoker** [comment]
FYI the legend doesn't fully appear in a (big) mobile resolution. Still, the result is pretty neat :) I think that this is something that we could use in manger-veggie too.

2015-11-19-031900_383x694_scrot

You'll also probably want to change the <code><title></code> and the favicon.

For you information, I have made this mockup of a possible way more mobile friendly interface that could inspire you https://github.com/gdesmott/manger-veggie/issues/10 This doesn't address the "currently the legend is bad" on which you are working but you seems to have the skills to do that if you wanted to (I don't currently, need to rtfm).

Regarding <code>tags_to_color()</code>, you can add a "vegoresto" app in which you can otherwrite this file by using the same path https://github.com/gdesmott/manger-veggie/blob/cc40afb7fb2ca8a5969a966ab847cbab3c74b4c9/restaurant/static/js/utils.js I never remember if you need to put your app before or after the one you want to otherwrite in <code>INSTALLED_APPS</code>. We could also think about a better mecanism for that.

**Comment by drzraf** [comment]
ok, changed the following:
* the legend overlay in its own file (so the home.haml diff stays small)
* fixed logo alignement

About link to /about, it's team non-sen...^Wdecision
And here is a screenshot of mapbox which was the choice of the team (I created an account and used the free API key, didn't look deeply but it allows for 50000 hit/day)

screen shot 2015-11-19 at 12 44 13

About tags_to_color, I'm sorry but I didn't quite understood what the solution would look like.

**Comment by Psycojoker** [comment]
> About tags_to_color, I'm sorry but I didn't quite understood what the solution would look like.

Something like that:

    python manage.py startapp vegoresto

Add "vegoresto" to the end of INSTALLED_APPS in vegoresto_settings.py

    mkdir -p vegoresto/static/js

And put inside of vegoresto/static/js/utils.js the content you want that will overwrite restaurant/static/js/utils.js

Check if "static/js/utils.js" as the correct content, otherwise, move vegoresto at the top of the INSTALLED_APPS to see if it changes something.

**Pull request merged**
