### PR TITLE
 vegoresto.fr: customizations

### PR DESCRIPTION
**Pull request by drzraf**
- moved files to their own app
- override utils.js to fix tags_to_color
- reworded /about

### CODE REVIEW

**Comment by Psycojoker** [comment]
Looks good to me :)

**Comment by drzraf** [comment]
Let's see later if utils can/have to be split, it currently only contains a couple of functions.
The fact is that having a distinct Django app help overriding assets (js), but didn't solve the point of make tag_to_color more generic.
Could we please push this one and postpone the discussion about tag-color customization in subsequent issue/PR?

**Comment by Psycojoker** [comment]
I'm in favor of merging this one too.

**Comment by gdesmott** [comment]
Merged & deployed.

**Pull request merged**
