### PR TITLE
vegoresto.fr: customizations

### PR DESCRIPTION
**Pull request by drzraf**

### CODE REVIEW

**Comment by Psycojoker** [comment]
@olethanh can you deploy this plz?

**Comment by drzraf** [comment]
thx.

plan to deploy it?

**Comment by olethanh** [comment]
Sorry have been drown in work lately so haven't had time to take a look, will try to deploy this by the end of the week

**Comment by olethanh** [comment]
It should be deployed, I don't know what the change where exactly so could you please confirm it's properly done?

**Pull request merged**
